#Checks for all the C system headers found in all the files

include(CheckFunctionExists)
include(CheckLibraryExists)
include(CheckIncludeFiles)

check_include_files(arpa/inet.h MXS_HAVE_ARPA_INET)
check_include_files(crypt.h MXS_HAVE_CRYPT)
check_include_files(ctype.h MXS_HAVE_CTYPE)
check_include_files(dirent.h MXS_HAVE_DIRENT)
check_include_files(dlfcn.h MXS_HAVE_DLFCN)
check_include_files(errno.h MXS_HAVE_ERRNO)
check_include_files(execinfo.h MXS_HAVE_EXECINFO)
check_include_files(fcntl.h MXS_HAVE_FCNTL)
check_include_files(ftw.h MXS_HAVE_FTW)
check_include_files(getopt.h MXS_HAVE_GETOPT)
check_include_files(ini.h MXS_HAVE_INI)
check_include_files(math.h MXS_HAVE_MATH)
check_include_files(memlog.h MXS_HAVE_MEMLOG)
check_include_files(netdb.h MXS_HAVE_NETDB)
check_include_files(netinet/in.h MXS_HAVE_NETINET_IN)
check_include_files(openssl/aes.h MXS_HAVE_OPENSSL_AES)
check_include_files(openssl/sha.h MXS_HAVE_OPENSSL_SHA)
check_include_files(pthread.h MXS_HAVE_PTHREAD)
check_include_files(pwd.h MXS_HAVE_PWD)
check_include_files(rdtsc.h MXS_HAVE_RDTSC)
check_include_files(regex.h MXS_HAVE_REGEX)
check_include_files(signal.h MXS_HAVE_SIGNAL)
check_include_files(stdarg.h MXS_HAVE_STDARG)
check_include_files(stdbool.h MXS_HAVE_STDBOOL)
check_include_files(stdint.h MXS_HAVE_STDINT)
check_include_files(stdio.h MXS_HAVE_STDIO)
check_include_files(stdlib.h MXS_HAVE_STDLIB)
check_include_files(string.h MXS_HAVE_STRING)
check_include_files(strings.h MXS_HAVE_STRINGS)
check_include_files(sys/epoll.h MXS_HAVE_SYS_EPOLL)
check_include_files(sys/ioctl.h MXS_HAVE_SYS_IOCTL)
check_include_files(syslog.h MXS_HAVE_SYSLOG)
check_include_files(sys/param.h MXS_HAVE_SYS_PARAM)
check_include_files(sys/socket.h MXS_HAVE_SYS_SOCKET)
check_include_files(sys/stat.h MXS_HAVE_SYS_STAT)
check_include_files(sys/time.h MXS_HAVE_SYS_TIME)
check_include_files(sys/types.h MXS_HAVE_SYS_TYPES)
check_include_files(sys/un.h MXS_HAVE_SYS_UN)
check_include_files(time.h MXS_HAVE_TIME)
check_include_files(unistd.h MXS_HAVE_UNISTD)

# Check for libraries MaxScale depends on
find_library(MXS_HAVE_LIBAIO NAMES aio)
if(NOT MXS_HAVE_LIBAIO)
  message(FATAL_ERROR "Could not find libaio")
endif()

find_library(MXS_HAVE_LIBSSL NAMES ssl)
if(NOT MXS_HAVE_LIBSSL)
  message(FATAL_ERROR "Could not find libssl")
endif()

find_library(MXS_HAVE_LIBCRYPT NAMES crypt)
if(NOT MXS_HAVE_LIBCRYPT)
  message(FATAL_ERROR "Could not find libcrypt")
endif()

find_library(MXS_HAVE_LIBCRYPTO NAMES crypto)
if(NOT MXS_HAVE_LIBCRYPTO)
  message(FATAL_ERROR "Could not find libcrypto")
endif()

find_library(MXS_HAVE_LIBZ NAMES z)
if(NOT MXS_HAVE_LIBZ)
  message(FATAL_ERROR "Could not find libz")
endif()

find_library(MXS_HAVE_LIBM NAMES m)
if(NOT MXS_HAVE_LIBM)
  message(FATAL_ERROR "Could not find libm")
endif()

find_library(MXS_HAVE_LIBDL NAMES dl)
if(NOT MXS_HAVE_LIBDL)
  message(FATAL_ERROR "Could not find libdl")
endif()

find_library(MXS_HAVE_LIBRT NAMES rt)
if(NOT MXS_HAVE_LIBRT)
  message(FATAL_ERROR "Could not find librt")
endif()

find_library(MXS_HAVE_LIBPTHREAD NAMES pthread)
if(NOT MXS_HAVE_LIBPTHREAD)
  message(FATAL_ERROR "Could not find libpthread")
endif()
